from Tkinter import *
form = Tk()
form.title("Welcome to nile university")
form.geometry('1280x800')
photo=PhotoImage(file='91.gif')
labl=Label(form,image=photo,bd=0)
labl.place(x=400,y=50)
a = Label(form ,text = " ID").place(x=0,y=0)
l=Label(form ,text = "/").place(x = 80,y=50)
e = Entry(show ='*')
e.place(x=35,y=15)

def window1():
       formm = Tk()
       formm.title("Registration")
       formm.geometry('700x700')
       PRESSURE = Label(formm,text = "Age  ",).place(x = 15, y = 0)
       SUGAR = Label(formm,text = "Gender",).place(x = 15, y = 70)
       PULSE = Label(formm,text = "Weight",).place(x = 15, y = 140)
       HEIGHT = Label(formm,text = "Height",).place(x = 15, y = 210)
       WEIGHT = Label(formm,text = "Dr Contact",).place(x = 15, y = 280)       
       P = Entry(formm, width = "30")
       P.place(x = 15, y = 30)
       S = Entry(formm,width = "30")
       S.place(x = 15, y = 110)
       PU = Entry(formm,width = "30")
       PU.place(x = 15, y = 180)
       H= Entry(formm,width = "30")
       H.place(x = 15, y = 250)
       W= Entry(formm,width = "30")
       W.place(x = 15, y = 320)
       f=open('medic.txt','a') 
       f.write(e.get())
       f.write('\n')
       f.close() 
       def window4():
              form3 = Tk()
              form3.title("")
              form3.geometry('700x700')
              Label(form3,text='Basic Personal Information').pack()
              PRESSURE = Label(form3,text = "Blood Glocuse Level",).place(x = 15, y = 0)
              SUGAR = Label(form3,text = "Pressure",).place(x = 15, y = 70)
              PULSE = Label(form3,text = "Immunization",).place(x = 15, y = 140)       
              Pi = Entry(form3, width = "30")
              Pi.place(x = 15, y = 30)
              Si = Entry(form3,width = "30")
              Si.place(x = 15, y = 110)
              PUi = Entry(form3,width = "30")
              PUi.place(x = 15, y = 170)
              p=open('lie.txt','w+')              
              p.write('Age:'+' '+P.get())
              p.write('\n')
              p.write('Gender:'+' '+S.get())
              p.write('\n')
              p.write('Weight:'+' '+PU.get())
              p.write('\n')
              p.write('Hight:'+' '+H.get())
              p.write('\n')
              p.write('Dr Contact:'+' '+W.get())
              p.write('\n')
              p.close()  
              formm.destroy()  
              def window3():
                     y=open('lie.txt','a')
                     y.write('Blood Glucose Level:'+' '+Pi.get())
                     y.write('\n')
                     y.write('Pressure:'+' '+Si.get())
                     y.write('\n')
                     y.write('Immunization:'+' '+PUi.get())
                     y.write('\n')
                     y.close()
                     form3.destroy()
              b=Button(form3 ,text='submit',bd=0,command=window3).place(x=15,y=210)         
       btn111=Button(formm,text='Next',bd=1,command=window4).place(x=15,y=360)       
btn11=Button(form,text='submit',bd=0,command=window1).place(x=10,y=50)


def window2():
       form2 = Tk()
       form2.title("")
       form2.geometry('300x300')   
       Label(form2,text='Enter Your Data').pack()
       a2 = Entry(form2,bd=1,show='*')
       a2.place(x=3,y=40)
       y2 = Label(form2 ,text = "ID")
       y2.place(x=0,y=10)
       def call2():
              a2 = Entry(form2)
              a2.place(x=3,y=40)
       def wi():
              file=open("medic.txt",'r+')
              Lines=file.readlines() 
              Ln=[]
              for i in Lines:
                     Ln.append(i.strip())
              if a2.get() in Ln :
                     if len(a2.get())>len(Ln[0]):
                            root = Tk()
                            root.title("Informations")
                            root.geometry('700x700')     
                            with open('lie.txt', "r") as we:
                                   Label(root, text= we.read(),fg='black').grid()          
                            root.mainloop()
              else:     
                     root1 = Tk()
                     root1.title("Error")
                     root1.geometry('200x200')
                     Label(root1,text='wrong ID').pack()
                     root1.mainloop()            
       btn1=Button(form2,text='submit',bd=0,command=wi).place(x=0,y=80)
l1=Button(form,text='Login',bd=0,command=window2).place(x=90,y=50)
mainloop()
